version: "3"

services:

  nginx:
    build: "./nginx" 
    image: "tomwhiston/private-registry:nginx-alpine"
    ports:
      - 2323:2323
    links:
      - registry:registry
      - bow:bow  
    volumes:
      - ./nginx/auth/conf.d:/etc/nginx/conf.d
      - ./nginx/auth/nginx.conf:/etc/nginx/nginx.conf:ro
    security_opt:
      - label=type:container_runtime_t

  registry:
    image: registry:2
    volumes:
      - ./data:/var/lib/registry
    security_opt:
      - label=type:container_runtime_t

  bow:
    image: evedel/bow
    volumes:
      - ./bow:/var/lib/bow
    environment:
      BS_LOG_SILENT: "yes"
      BS_TIME_WATCH: "no"
    security_opt:
      - label=type:container_runtime_t

        
