apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: bow
  name: bow
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: evedel/bow
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
