apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: tomwhiston/private-registry:nginx-alpine
    generation: null
    importPolicy: {}
    name: nginx-alpine
status:
  dockerImageRepository: ""
