apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose --provider openshift -o openshift/ --file
      docker-compose.yml convert --build build-config
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
  - name: "2323"
    port: 2323
    targetPort: 2323
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
