apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose --provider openshift -o openshift/ --file
      docker-compose.yml convert --build build-config
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    io.kompose.service: nginx
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image: ' '
        name: nginx
        ports:
        - containerPort: 2323
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-claim0
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-claim1
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: nginx-claim0
        persistentVolumeClaim:
          claimName: nginx-claim0
      - name: nginx-claim1
        persistentVolumeClaim:
          claimName: nginx-claim1
          readOnly: true
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - nginx
      from:
        kind: ImageStreamTag
        name: nginx:nginx-alpine
    type: ImageChange
status: {}
