apiVersion: v1
data:
  conf: "events {\n    worker_connections  1024;\n}\n\nhttp {\n\n  upstream docker-registry
    {\n    server registry:5000;\n  }\n\n  upstream frontend {\n    server bow:19808;
    \ \n  }\n\n  ## Set a variable to help us decide if we need to add the\n  ## 'Docker-Distribution-Api-Version'
    header.\n  ## The registry always sets this header.\n  ## In the case of nginx
    performing auth, the header is unset\n  ## since nginx is auth-ing before proxying.\n
    \ map $upstream_http_docker_distribution_api_version $docker_distribution_api_version
    {\n    '' 'registry/2.0';\n  }\n\n  server {\n    listen 2323;\n    server_name
    _;\n\n    # SSL\n#    ssl_certificate /etc/nginx/conf.d/domain.crt;\n#    ssl_certificate_key
    /etc/nginx/conf.d/domain.key;\n\n    # Recommendations from https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html\n#
    \   ssl_protocols TLSv1.1 TLSv1.2;\n#    ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';\n#
    \   ssl_prefer_server_ciphers on;\n#    ssl_session_cache shared:SSL:10m;\n\n
    \   # disable any limits to avoid HTTP 413 for large image uploads\n    client_max_body_size
    0;\n\n    # required to avoid HTTP 411: see Issue #1486 (https://github.com/moby/moby/issues/1486)\n
    \   chunked_transfer_encoding on;\n\n   location / {\n\n      # To add basic authentication
    to v2 use auth_basic setting.\n      auth_basic \"Registry realm\";\n      auth_basic_user_file
    /etc/nginx/conf.d/nginx.htpasswd;\n\n      proxy_pass                          http://frontend;\n
    \     proxy_set_header  Host              $http_host;   \n      proxy_set_header
    \ X-Real-IP         $remote_addr; \n      proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;\n
    \     proxy_set_header  X-Forwarded-Proto $scheme;\n      proxy_read_timeout                  900;\n
    \   }\n \n    location /v2/ {\n      # Do not allow connections from docker 1.5
    and earlier\n      # docker pre-1.6.0 did not properly set the user agent on ping,
    catch \"Go *\" user agents\n      if ($http_user_agent ~ \"^(docker\\/1\\.(3|4|5(?!\\.[0-9]-dev))|Go
    ).*$\" ) {\n        return 404;\n      }\n\n      # To add basic authentication
    to v2 use auth_basic setting.\n      auth_basic \"Registry realm\";\n      auth_basic_user_file
    /etc/nginx/conf.d/nginx.htpasswd;\n\n      ## If $docker_distribution_api_version
    is empty, the header is not added.\n      ## See the map directive above where
    this variable is defined.\n      add_header 'Docker-Distribution-Api-Version'
    $docker_distribution_api_version always;\n\n      proxy_pass                          http://docker-registry;\n
    \     proxy_set_header  Host              $http_host;   # required for docker
    client's sake\n      proxy_set_header  X-Real-IP         $remote_addr; # pass
    on real client's IP\n      proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;\n
    \     proxy_set_header  X-Forwarded-Proto $scheme;\n      proxy_read_timeout                  900;\n
    \   }\n\n }\n}\n"
  htpasswd: testuser:$2y$05$8stJBeDOftFrnIYAZhEPe.QsIbXq4wbjMYGVDAAyVG2euuodhOcaK
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx
