apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose --provider openshift -o openshift/ --file
      docker-compose.yml convert --build build-config
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  clusterIP: None
  ports:
  - name: redis-port 
    port: 6379
    targetPort: 0
  selector:
    io.kompose.service: redis
status:
  loadBalancer: {}
