apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose --provider openshift -o openshift/ --file
      docker-compose.yml convert --build build-config
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: redis 
  name: redis 
spec:
  replicas: 1
  selector:
    io.kompose.service: redis 
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis 
    spec:
      containers:
      - image: ' '
        name: redis  
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: redis-claim0
      restartPolicy: Always
      volumes:
      - name: redis-claim0
        persistentVolumeClaim:
          claimName: redis-claim0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - redis 
      from:
        kind: ImageStreamTag
        name: redis:latest
    type: ImageChange
status: {}
