apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose --provider openshift -o openshift/ --file
      docker-compose.yml convert --build build-config
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: registry
  name: registry
spec:
  replicas: 1
  selector:
    io.kompose.service: registry
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: registry
    spec:
      containers:
      - image: ' '
        name: registry
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry-claim0
      restartPolicy: Always
      volumes:
      - name: registry-claim0
        persistentVolumeClaim:
          claimName: registry-claim0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - registry
      from:
        kind: ImageStreamTag
        name: registry:2
    type: ImageChange
status: {}
